# Generated by Django 5.1.2 on 2024-10-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=90)),
                ('nome', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
    ]
