# Generated by Django 5.1.2 on 2024-10-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=90)),
                ('nome', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
    ]
